In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt

In [2]:
torch.__version__

'1.13.1'

In [3]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1660'

In [4]:
tn = torch.tensor(5)
Tn = torch.Tensor(5)

In [5]:
print(tn, tn.dtype, tn.item())

tensor(5) torch.int64 5


In [6]:
print(Tn, Tn.dtype)

tensor([1.3452e-43, 0.0000e+00, 1.1210e-43, 0.0000e+00, 3.4812e-41]) torch.float32


In [7]:
tn.device

device(type='cpu')

In [8]:
tn = torch.tensor([1, 2, 5], dtype=int, requires_grad=False)
print(tn, tn.shape, tn.size())

tensor([1, 2, 5]) torch.Size([3]) torch.Size([3])


In [9]:
tn = torch.tensor([[2, 1], [3, 4]])
print(tn, tn.shape)

tensor([[2, 1],
        [3, 4]]) torch.Size([2, 2])


In [10]:
tn = torch.tensor(
    [
        [
            [1, 2], [3, 4], [5, 6]
        ],
        [
            [1, 2], [3, 4], [5, 6]
        ],
        [
            [1, 2], [3, 4], [5, 6]
        ]
    ])
print(tn, tn.shape)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]) torch.Size([3, 3, 2])


In [11]:
tn = torch.tensor([[[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]],
                   [[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]]])
tn

tensor([[[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]],


        [[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]]])

In [12]:
print(tn.min(), tn.max())

tensor(1) tensor(6)


In [13]:
tn.numel()

36

In [14]:
arr = np.array([4, 6, 7])
type(arr)

numpy.ndarray

In [15]:
t = torch.as_tensor(arr, device='cuda')
type(t)

torch.Tensor

In [16]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
torch.empty(5, 5)

tensor([[1.5134e-42, 1.4493e-39, 0.0000e+00, 0.0000e+00, 1.2612e-44],
        [1.4493e-39, 1.6315e-05, 0.0000e+00, 1.5120e-42, 1.4500e-39],
        [0.0000e+00, 0.0000e+00, 1.2612e-44, 1.4550e-39, 1.6315e-05],
        [0.0000e+00, 1.5106e-42, 1.4586e-39, 0.0000e+00, 0.0000e+00],
        [1.2612e-44, 1.4493e-39, 1.6315e-05, 0.0000e+00, 1.4938e-42]])

In [18]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.eye(6, 6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [20]:
torch.full((3, 3), -1)

tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]])

In [21]:
torch.rand(2, 2)

tensor([[0.6071, 0.1020],
        [0.3108, 0.4797]])

In [22]:
x = torch.rand(1, 3)
y = torch.rand(1, 3)
torch.cat((x, y), 0)

tensor([[0.3211, 0.1694, 0.9556],
        [0.9093, 0.1339, 0.7996]])

In [23]:
r = torch.tensor([[6, 5, 4], [6, 5, 4]])
r.shape

torch.Size([2, 3])

In [24]:
re = torch.reshape(r, (3, 2))
re

tensor([[6, 5],
        [4, 6],
        [5, 4]])

In [25]:
w = torch.tensor([[[
    [1, 3], [4, 6], [7, 9]
], [
    [1, 3], [4, 6], [7, 9]
], [
    [1, 3], [4, 6], [7, 9]
]]])

In [26]:
w.size()

torch.Size([1, 3, 3, 2])

In [27]:
q = torch.squeeze(w, 0)
print(q.size())
q

torch.Size([3, 3, 2])


tensor([[[1, 3],
         [4, 6],
         [7, 9]],

        [[1, 3],
         [4, 6],
         [7, 9]],

        [[1, 3],
         [4, 6],
         [7, 9]]])

In [28]:
k = torch.tensor([1, 2, 3, 4])
k

tensor([1, 2, 3, 4])

In [29]:
f = torch.unsqueeze(k, 1)
f.size()

torch.Size([4, 1])

In [30]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

tensor([[0.1341, 0.6827, 0.8115],
        [0.8174, 0.3856, 0.5720]])
tensor([[0.7655, 0.5835, 0.1154],
        [0.4751, 0.9003, 0.8270]])


In [31]:
torch.where(x >= 0.5, x, y)

tensor([[0.7655, 0.6827, 0.8115],
        [0.8174, 0.9003, 0.5720]])

In [32]:
torch.randperm(5)

tensor([0, 1, 2, 3, 4])

In [33]:
n1 = torch.normal(
    mean=torch.arange(0.1, 0.9),
    std=torch.arange(1., 6.)
)
n1

tensor([-0.0321,  0.2203, -6.7216, -2.2608,  1.2439])

In [34]:
n2 = torch.normal(1, 2, size=(3, 4))
n2

tensor([[-1.2631,  0.4873, -2.2336, -1.3495],
        [ 5.7044,  1.7527, -0.9630, -3.3137],
        [ 0.9507,  0.3954,  1.3923, -1.1170]])

In [35]:
torch.save(n1, 'normal1.pt')

In [36]:
load_n1 = torch.load('normal1.pt')
load_n1

tensor([-0.0321,  0.2203, -6.7216, -2.2608,  1.2439])

In [37]:
g1 = torch.tensor(3, dtype=float, requires_grad=True)
g1

tensor(3., dtype=torch.float64, requires_grad=True)

In [38]:
g2 = torch.tensor(5, dtype=float, requires_grad=False)
g2

tensor(5., dtype=torch.float64)

In [39]:
a = torch.tensor(3, dtype=float, requires_grad=True)
b = torch.tensor(5, dtype=float, requires_grad=False)

In [40]:
F = a * a + b * a + 5
F.backward()
a.grad

tensor(11., dtype=torch.float64)

In [41]:
a = torch.tensor(3, dtype=float, requires_grad=False)
b = torch.tensor(5, dtype=float, requires_grad=True)

In [42]:
F = a * a + b * a + 5
F.backward()
b.grad

tensor(3., dtype=torch.float64)

In [43]:
x = torch.tensor(6, dtype=float, requires_grad=True)

with torch.no_grad():
    y = x * 2

y.requires_grad

False

In [44]:
x = torch.tensor(6, dtype=float, requires_grad=True)

with torch.enable_grad():
    y = x * 2

y.requires_grad

True

In [45]:
m = torch.rand(4)
m

tensor([0.7656, 0.6245, 0.4575, 0.3737])

In [46]:
torch.cos(m)

tensor([0.7209, 0.8112, 0.8972, 0.9310])

In [47]:
print(torch.amin(m), torch.amax(m))

tensor(0.3737) tensor(0.7656)


In [48]:
torch.div(m, 0.3)

tensor([2.5522, 2.0817, 1.5250, 1.2458])

In [49]:
torch.sqrt(m)

tensor([0.8750, 0.7903, 0.6764, 0.6113])

In [50]:
torch.sub(m, 1)

tensor([-0.2344, -0.3755, -0.5425, -0.6263])

In [51]:
torch.exp(m)

tensor([2.1504, 1.8674, 1.5801, 1.4532])

In [52]:
mp = torch.add(m, 8)
print(m)
print(mp)

tensor([0.7656, 0.6245, 0.4575, 0.3737])
tensor([8.7656, 8.6245, 8.4575, 8.3737])


In [53]:
torch.sum(m)

tensor(2.2214)

In [54]:
torch.sum(mp)

tensor(34.2214)

In [55]:
torch.norm(m)

tensor(1.1512)

In [56]:
torch.norm(m, p='fro')

tensor(1.1512)

In [57]:
x = torch.tensor([1, 2, -1])
y = torch.tensor([1, 2, -1])

In [58]:
torch.eq(x, y)

tensor([True, True, True])

In [59]:
torch.equal(x, y)

True

In [60]:
x = torch.tensor([1, 5, -1])
y = torch.tensor([1, 2, 0])

In [61]:
torch.ge(x, y)

tensor([ True,  True, False])

### Ali Farajnia