In [2]:
import torch
import numpy as np
from matplotlib import pyplot as plt

In [3]:
torch.__version__

'1.13.1+cu117'

In [4]:
torch.cuda.get_device_name()

'GeForce GTX 1660'

In [5]:
tn = torch.tensor(5)
Tn = torch.Tensor(5)

In [6]:
print(tn, tn.dtype, tn.item())

tensor(5) torch.int64 5


In [7]:
print(Tn, Tn.dtype)

tensor([6.6830e+22, 1.2712e+31, 1.1626e+27, 1.8936e+23, 2.0112e-19]) torch.float32


In [8]:
tn.device

device(type='cpu')

In [9]:
tn = torch.tensor([1, 2, 5], dtype=int, requires_grad=False)
print(tn, tn.shape, tn.size())

tensor([1, 2, 5]) torch.Size([3]) torch.Size([3])


In [10]:
tn = torch.tensor([[2, 1], [3, 4]])
print(tn, tn.shape)

tensor([[2, 1],
        [3, 4]]) torch.Size([2, 2])


In [11]:
tn = torch.tensor(
    [
        [
            [1, 2], [3, 4], [5, 6]
        ],
        [
            [1, 2], [3, 4], [5, 6]
        ],
        [
            [1, 2], [3, 4], [5, 6]
        ]
    ])
print(tn, tn.shape)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]) torch.Size([3, 3, 2])


In [12]:
tn = torch.tensor([[[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]],
                   [[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]]])
tn

tensor([[[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]],


        [[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]]])

In [13]:
print(tn.min(), tn.max())

tensor(1) tensor(6)


In [14]:
tn.numel()

36

In [15]:
arr = np.array([4, 6, 7])
type(arr)

numpy.ndarray

In [16]:
t = torch.as_tensor(arr, device='cuda')
type(t)

torch.Tensor

In [17]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.empty(5, 5)

tensor([[1.5766e-19, 1.0256e-08, 2.5637e-09, 3.1643e+12, 6.9363e-07],
        [4.3208e-05, 1.0502e-05, 1.2964e+16, 2.1707e-18, 7.0952e+22],
        [1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31, 3.2608e-12],
        [1.7728e+28, 7.0367e+22, 2.1715e-18, 2.5814e-09, 1.7203e-04],
        [8.5085e-07, 2.0773e+20, 1.6517e-04, 1.0415e-11, 2.5786e-09]])

In [19]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
torch.eye(6, 6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [21]:
torch.full((3, 3), -1)

tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]])

In [22]:
torch.rand(2, 2)

tensor([[0.4344, 0.8814],
        [0.7990, 0.4745]])

In [23]:
x = torch.rand(1, 3)
y = torch.rand(1, 3)
torch.cat((x, y), 0)

tensor([[0.5485, 0.1209, 0.1019],
        [0.0061, 0.8385, 0.1305]])

In [24]:
r = torch.tensor([[6, 5, 4], [6, 5, 4]])
r.shape

torch.Size([2, 3])

In [25]:
re = torch.reshape(r, (3, 2))
re

tensor([[6, 5],
        [4, 6],
        [5, 4]])

In [26]:
w = torch.tensor([[[
    [1, 3], [4, 6], [7, 9]
], [
    [1, 3], [4, 6], [7, 9]
], [
    [1, 3], [4, 6], [7, 9]
]]])

In [27]:
w.size()

torch.Size([1, 3, 3, 2])

In [28]:
q = torch.squeeze(w, 0)
print(q.size())
q

torch.Size([3, 3, 2])


tensor([[[1, 3],
         [4, 6],
         [7, 9]],

        [[1, 3],
         [4, 6],
         [7, 9]],

        [[1, 3],
         [4, 6],
         [7, 9]]])

In [29]:
k = torch.tensor([1, 2, 3, 4])
k

tensor([1, 2, 3, 4])

In [30]:
f = torch.unsqueeze(k, 1)
f.size()

torch.Size([4, 1])

In [31]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

tensor([[0.2828, 0.8476, 0.1037],
        [0.0270, 0.6736, 0.1414]])
tensor([[0.3157, 0.2384, 0.4457],
        [0.3363, 0.4855, 0.4526]])


In [32]:
torch.where(x >= 0.5, x, y)

tensor([[0.3157, 0.8476, 0.4457],
        [0.3363, 0.6736, 0.4526]])

In [33]:
torch.randperm(5)

tensor([2, 4, 3, 0, 1])

In [34]:
n1 = torch.normal(
    mean=torch.arange(0.1, 0.9),
    std=torch.arange(1., 6.)
)
n1

tensor([ 0.6143, -3.5707,  5.3039,  0.1319,  4.0713])

In [35]:
n2 = torch.normal(1, 2, size=(3, 4))
n2

tensor([[ 0.4007,  2.4442,  3.7547,  3.1817],
        [ 2.3365,  4.0983,  1.7614,  0.5706],
        [ 1.1760, -4.4132,  0.4721,  5.0824]])

In [36]:
torch.save(n1, 'normal1.pt')

In [37]:
load_n1 = torch.load('normal1.pt')
load_n1

tensor([ 0.6143, -3.5707,  5.3039,  0.1319,  4.0713])

In [38]:
g1 = torch.tensor(3, dtype=float, requires_grad=True)
g1

tensor(3., dtype=torch.float64, requires_grad=True)

In [39]:
g2 = torch.tensor(5, dtype=float, requires_grad=False)
g2

tensor(5., dtype=torch.float64)

In [44]:
a = torch.tensor(3, dtype=float, requires_grad=True)
b = torch.tensor(5, dtype=float, requires_grad=False)

In [51]:
F = a * a + b * a + 5
F.backward()
a.grad

tensor(77., dtype=torch.float64)

In [52]:
a = torch.tensor(3, dtype=float, requires_grad=False)
b = torch.tensor(5, dtype=float, requires_grad=True)

In [55]:
F = a * a + b * a + 5
F.backward()
b.grad

tensor(9., dtype=torch.float64)

In [56]:
x = torch.tensor(6, dtype=float, requires_grad=True)

with torch.no_grad():
    y = x * 2

y.requires_grad

False

In [57]:
x = torch.tensor(6, dtype=float, requires_grad=True)

with torch.enable_grad():
    y = x * 2

y.requires_grad

True