In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cu117'

In [3]:
torch.cuda.get_device_name()

'GeForce GTX 1660'

In [4]:
tn = torch.tensor(5)
Tn = torch.Tensor(5)

In [5]:
print(tn , tn.dtype , tn.item())

tensor(5) torch.int64 5


In [6]:
print(Tn , Tn.dtype)

tensor([0., 0., 0., 0., 0.]) torch.float32


In [7]:
tn.device

device(type='cpu')

In [8]:
tn = torch.tensor([1,2,5],dtype= int, requires_grad= False)
print(tn , tn.shape , tn.size())

tensor([1, 2, 5]) torch.Size([3]) torch.Size([3])


In [9]:
tn = torch.tensor([[2,1],[3,4]])
print(tn , tn.shape)

tensor([[2, 1],
        [3, 4]]) torch.Size([2, 2])


In [10]:
tn = torch.tensor(
    [
        [
            [1,2],[3,4],[5,6]
        ],
        [
            [1,2],[3,4],[5,6]
        ],
        [
            [1,2],[3,4],[5,6]
        ]
    ])
print(tn , tn.shape)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]) torch.Size([3, 3, 2])


In [11]:
tn = torch.tensor([[[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]],[[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]]])
tn

tensor([[[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]],


        [[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]]])

In [12]:
print(tn.min() , tn.max())

tensor(1) tensor(6)
