In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.13.1+cu117'

In [3]:
torch.cuda.get_device_name()

'GeForce GTX 1660'

In [4]:
tn = torch.tensor(5)
Tn = torch.Tensor(5)

In [5]:
print(tn, tn.dtype, tn.item())

tensor(5) torch.int64 5


In [6]:
print(Tn, Tn.dtype)

tensor([0., 0., 0., 0., 0.]) torch.float32


In [7]:
tn.device

device(type='cpu')

In [8]:
tn = torch.tensor([1, 2, 5], dtype=int, requires_grad=False)
print(tn, tn.shape, tn.size())

tensor([1, 2, 5]) torch.Size([3]) torch.Size([3])


In [9]:
tn = torch.tensor([[2, 1], [3, 4]])
print(tn, tn.shape)

tensor([[2, 1],
        [3, 4]]) torch.Size([2, 2])


In [10]:
tn = torch.tensor(
    [
        [
            [1, 2], [3, 4], [5, 6]
        ],
        [
            [1, 2], [3, 4], [5, 6]
        ],
        [
            [1, 2], [3, 4], [5, 6]
        ]
    ])
print(tn, tn.shape)

tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]) torch.Size([3, 3, 2])


In [11]:
tn = torch.tensor([[[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]],
                   [[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]]])
tn

tensor([[[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]],


        [[[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]],

         [[1, 2],
          [3, 4],
          [5, 6]]]])

In [12]:
print(tn.min(), tn.max())

tensor(1) tensor(6)


In [13]:
tn.numel()

36

In [14]:
arr = np.array([4, 6, 7])
type(arr)

numpy.ndarray

In [15]:
t = torch.as_tensor(arr, device='cuda')
type(t)

torch.Tensor

In [16]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
torch.empty(5, 5)

tensor([[0.0000e+00, 1.6217e-19, 7.7052e+31, 7.2148e+22, 1.5766e-19],
        [1.0256e-08, 2.5637e-09, 3.1643e+12, 1.0838e-08, 1.6506e-07],
        [1.7470e-04, 1.2892e+16, 2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 5.3363e-08, 5.3933e-05, 1.0562e-05]])

In [18]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.eye(6, 6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [20]:
torch.full((3, 3), -1)

tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]])

In [21]:
torch.rand(2, 2)

tensor([[0.2647, 0.1877],
        [0.2263, 0.7775]])

In [22]:
x = torch.rand(1, 3)
y = torch.rand(1, 3)
torch.cat((x, y), 0)

tensor([[0.3510, 0.5796, 0.9594],
        [0.7907, 0.3036, 0.1446]])

In [23]:
r = torch.tensor([[6, 5, 4], [6, 5, 4]])
r.shape

torch.Size([2, 3])

In [24]:
re = torch.reshape(r, (3, 2))
re

tensor([[6, 5],
        [4, 6],
        [5, 4]])

In [25]:
w = torch.tensor([[[
    [1, 3], [4, 6], [7, 9]
], [
    [1, 3], [4, 6], [7, 9]
], [
    [1, 3], [4, 6], [7, 9]
]]])

In [26]:
w.size()

torch.Size([1, 3, 3, 2])

In [27]:
q = torch.squeeze(w, 0)
print(q.size())
q

torch.Size([3, 3, 2])


tensor([[[1, 3],
         [4, 6],
         [7, 9]],

        [[1, 3],
         [4, 6],
         [7, 9]],

        [[1, 3],
         [4, 6],
         [7, 9]]])

In [28]:
k = torch.tensor([1, 2, 3, 4])
k

tensor([1, 2, 3, 4])

In [29]:
f = torch.unsqueeze(k, 1)
f.size()

torch.Size([4, 1])

In [30]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

tensor([[0.1889, 0.6415, 0.2186],
        [0.7059, 0.1831, 0.7175]])
tensor([[0.6997, 0.4022, 0.7501],
        [0.7019, 0.1978, 0.3528]])


In [31]:
torch.where(x >= 0.5, x, y)

tensor([[0.6997, 0.6415, 0.7501],
        [0.7059, 0.1978, 0.7175]])

In [32]:
torch.randperm(5)

tensor([1, 3, 0, 2, 4])